language: perl

install:
  - perlbrew list
  - cpanm -n Dist::Zilla
  - ./travis/install-dzil-plugin-author-plicease.sh
  - cpanm -n Dist::Zilla::Plugin::Bootstrap::ShareDir::Module
  - cpanm -n Dist::Zilla::Plugin::Bootstrap::lib
  - cpanm -n Dist::Zilla::PluginBundle::Git || true
  - cpanm -n Dist::Zilla::Plugin::Meta::Dynamic::Config
  - cpanm -n Capture::Tiny
  - cpanm -n Dist::Zilla::Util::CurrentCmd
  - cpanm -n Test::File Test::Dir
  - dzil authordeps --missing | cpanm -n
  - dzil listdeps   --missing | cpanm -n

perl:
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.20"
  - "5.22"
  - "5.24"
  - "5.26"

script: dzil test -v

sudo: false
